### ISSUE TITLE
Fix Ref Error caused by strict mode

### ISSUE THREAD

**Issue by Unesdala** [WebJamApps/breakpointministries#128]
```
console.error
    Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of ResizeDetector which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
        at div
        at Homepage (/home/joshua/WebJamApps/breakpointministries/src/containers/Homepage/index.tsx:43:5)
        at ResizeDetector (/home/joshua/WebJamApps/breakpointministries/node_modules/react-resize-detector/src/ResizeDetector.tsx:116:5)
        at ResizeDetectorHOC (/home/joshua/WebJamApps/breakpointministries/node_modules/react-resize-detector/src/withResizeDetector.tsx:10:3)
        at withResizeDetector(Homepage)
        at ConnectFunction (/home/joshua/WebJamApps/breakpointministries/node_modules/react-redux/lib/components/connectAdvanced.js:235:41)
        at Route (/home/joshua/WebJamApps/breakpointministries/node_modules/react-router/cjs/react-router.js:464:29)
        at Switch (/home/joshua/WebJamApps/breakpointministries/node_modules/react-router/cjs/react-router.js:666:29)
        at div
        at AppTemplate (/home/joshua/WebJamApps/breakpointministries/src/App/AppTemplate.tsx:34:5)
        at ConnectFunction (/home/joshua/WebJamApps/breakpointministries/node_modules/react-redux/lib/components/connectAdvanced.js:235:41)
        at C (/home/joshua/WebJamApps/breakpointministries/node_modules/react-router/modules/withRouter.js:14:13)
        at Router (/home/joshua/WebJamApps/breakpointministries/node_modules/react-router/cjs/react-router.js:95:30)
        at BrowserRouter (/home/joshua/WebJamApps/breakpointministries/node_modules/react-router-dom/cjs/react-router-dom.js:75:35)
        at div
        at App (/home/joshua/WebJamApps/breakpointministries/src/App/index.tsx:31:5)
        at ConnectFunction (/home/joshua/WebJamApps/breakpointministries/node_modules/react-redux/lib/components/connectAdvanced.js:235:41)
        at PersistGate (/home/joshua/WebJamApps/breakpointministries/node_modules/redux-persist/lib/integration/react.js:40:5)
        at Provider (/home/joshua/WebJamApps/breakpointministries/node_modules/react-redux/lib/components/Provider.js:21:20)
        at MainStack

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at findHostInstanceWithWarning (node_modules/react-dom/cjs/react-dom.development.js:25406:13)
      at Object.findDOMNode (node_modules/react-dom/cjs/react-dom.development.js:26067:12)
      at ResizeDetector._this.getElement (node_modules/react-resize-detector/src/ResizeDetector.tsx:201:28)
      at ResizeDetector._this.attachObserver (node_modules/react-resize-detector/src/ResizeDetector.tsx:172:26)
      at ResizeDetector.Object.<anonymous>.ResizeDetector.componentDidMount (node_modules/react-resize-detector/src/ResizeDetector.tsx:138:10)
```

**Comment by JoshuaVSherman** [comment]
@Unesdala do you need help with this?
